spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gc
    username: root
    password: kk123456
  jpa:
    hibernate:
      ddl-auto: update
      #实现@id主键能自动增长，@GeneratedValue能生效，这个必须设置成false
      use-new-id-generator-mappings: false
    show-sql: true
